[workspace]
resolver = "2"
members = ["front-line-router", "front-line-derive", "front-line"]

[workspace.dependencies]
memchr = "2.6.4"
proc-macro2 = "1.0.67"
quote = "1.0.33"
regex = "1.9.6"
syn = "2.0.37"
thiserror = "1.0.49"
rstest = "0.18.2"
